name: CI

on:
    push:     
      branches: ['sit', 'uat', 'main']
    pull_request:   
      branches: ['sit', 'uat', 'main']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v3
            
            - name: build
              run: |
                mvn clean install -DartifactId=demo-${{ github.ref_name }}