name: Release

on:
    workflow_dispatch:       

permissions:
  contents: write

jobs:
    build-release:
        runs-on: ubuntu-latest        
        if: ${{ contains(fromJson('["sit", "uat"]')  , github.ref_name) }}
        steps:
            - name: Code Checkout
              uses: actions/checkout@v3
              
            - name: List files
              run: |
                ls -ltr
                cat ver.txt           

           
            - name: Release tags and package for ${{ github.ref_name }}
              run: |
                git config user.name $GIT_USERNAME
                mvn release:clean release:prepare release:perform -s ci_settings.xml
              env:
                GITHUB_TOKEN: ${{ secrets.PAT }}
                GIT_USERNAME: ${{ github.actor }}
                GIT_PASSWORD: ${{ secrets.PAT }}                
                NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v3.1.3
              with:               
                name: BuildArtifacts             
                path: "target/checkout/*/*.war"
                
            
