name: Release

on:
    workflow_dispatch:       

permissions:
  contents: write

jobs:
    verify-branch-name:
        runs-on: ubuntu-latest
        steps:
            - name: Get Branch Name
              run: |
                echo "Branch Name: ${{github.ref_name}}"

    build-release:
        runs-on: ubuntu-latest
        needs: verify-branch-name
        if: ${{ contains(fromJson('["sit", "uat"]')  , github.ref_name) }}
        steps:
            - name: Code Checkout
              uses: actions/checkout@v3
              
            - name: List files
              run: |
                ls -ltr
                cat ver.txt                

            - name: build
              run: |
                mvn clean install -DartifactId=demo-${{ github.ref_name }}

            - name: Release tags and package for ${{ github.ref_name }}
              run: |
                git config user.name $GIT_USERNAME
                mvn release:clean release:prepare release:perform -s ci_settings.xml -DartifactId=demo-${{ github.ref_name }}
              env:
                GITHUB_TOKEN: ${{ secrets.PAT }}
                GIT_USERNAME: ${{ github.actor }}
                GIT_PASSWORD: ${{ secrets.PAT }}                
                NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}                