name: Release

on:
    workflow_dispatch:       

permissions:
  contents: write

jobs:
    build-release:
        runs-on: ubuntu-latest
        if: ${{ contains(fromJson('["refs/heads/sit", "refs/heads/uat"]')  , github.ref) }}
        steps:
            - name: Code Checkout
              uses: actions/checkout@v3
              with:
                ref: ${{ github.ref }}
            
            - name: build
              run: |
                mvn clean install

            - name: Release tags and package for ${{ github.ref }}
              run: |
                git config user.name $GIT_USERNAME
                mvn release:clean release:prepare release:perform -s ci_settings.xml
              env:
                GITHUB_TOKEN: ${{ secrets.PAT }}
                GIT_USERNAME: ${{ github.actor }}
                GIT_PASSWORD: ${{ secrets.PAT }}                
                NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
                