name: Release

on:
    workflow_dispatch:
        inputs:
            BRANCH:
                type: choice                
                description: branch for release
                options:
                    - sit
                    - uat 

permissions:
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v3
              with:
                ref: ${{ inputs.BRANCH }}
            
            - name: build
              run: |
                mvn clean install

    release:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Code Checkout
              uses: actions/checkout@v3
              with:
                ref: ${{ inputs.BRANCH }}
            
            - name: Release tags and package for ${{ inputs.BRANCH }}
              run: |
                git config user.name $GIT_USERNAME
                mvn release:clean release:prepare release:perform -s ci_settings.xml
              env:
                GITHUB_TOKEN: ${{ secrets.PAT }}
                GIT_USERNAME: ${{ github.actor }}
                GIT_PASSWORD: ${{ secrets.PAT }}                
                NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

                
                